services:
  db:
    image: postgres:16-alpine
    container_name: krs_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - config.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: krs_app
    build:
      context: /app
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "50051:50051"
    restart: on-failure

volumes:
  pgdata: